parameters:
    matthimatiker_command_locking.console.default_lock_manager_alias: "file"

services:
    matthimatiker_command_locking.console.locking_listener:
        class: Matthimatiker\CommandLockingBundle\EventListener\CommandLockingListener
        arguments: ["%matthimatiker_command_locking.console.default_lock_manager_alias%"]
        tags:
            - { name: kernel.event_subscriber }

    matthimatiker_command_locking.console.lock_manager.file:
        class: Matthimatiker\CommandLockingBundle\Locking\FileLockManager
        arguments: ["%kernel.cache_dir%/command-locks"]
        tags:
            - { name: matthimatiker_command_locking.console.lock_manager, alias: file }
