services:
    matthimatiker_command_locking.console.locking_listener:
        class: Matthimatiker\CommandLockingBundle\EventListener\CommandLockingListener
        arguments: ["default"]
        tags:
            - { name: kernel.event_subscriber }
